name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install root dependencies
        run: bun install

      - name: Install Backend Dependencies
        run: cd server && bun install

      - name: Run lint
        run: bun run lint

      - name: Check formatting
        run: bun run format:check

      - name: Run typecheck
        run: bun run typecheck

      - name: Run test suite
        run: bun run test
        env:
          DB_FILE_NAME: "sqlite.db"
